name: Bug Report
description: Create a report to help us improve
labels:
  - bug
body:
  - type: textarea
    id: textarea-0
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
  - type: input
    id: input-1
    validations:
      required: true
    attributes:
      label: App Version
      description: What release of the app you're using?
      placeholder: v1.0.0
  - type: input
    id: input-2
    validations:
      required: true
    attributes:
      label: Python Log
      description: Please paste here the full Python Traceback. (The text in red)
      placeholder: Traceback (most recent call last)
